markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: 2..3
plugins:
  - github-pages
remote_theme: rakutentech/android-buildconfig@gh-pages-theme

title: Mini App SDK for JS
description: Use Android/iOS device features and other extended features in mini apps.
repository: rakutentech/js-miniapps

docs_path: docs
api_docs_path: api

collections:
  versions: