/** @internal */

/**
 * Main entry point for SDK
 */

import {
  Reward,
  CustomPermission,
  CustomPermissionName,
  CustomPermissionStatus,
  CustomPermissionResult,
  ShareInfo,
  ScreenOrientation,
  AccessTokenData,
  Contact,
  Points,
  HostEnvironmentInfo,
  DownloadFileHeaders,
  Platform,
  MessageToContact,
  AuthorizationFailureError,
  AudienceNotSupportedError,
  DownloadFailedError,
  DownloadHttpError,
  InvalidUrlError,
  MiniAppError,
  SaveFailureError,
  ScopesNotSupportedError,
  SecureStorageFullError,
  SecureStorageBusyError,
  SecureStorageUnavailableError,
  SecureStorageIOError,
  MiniAppSecureStorageEvents,
  CloseAlertInfo,
  ProductInfo,
  ProductPrice,
  PurchasedProductInfo,
  PurchaseFailedError,
  ConsumeFailedError,
  ProductNotFoundError,
  ProductPurchasedAlreadyError,
  UserCancelledPurchaseError,
  HostThemeColor,
  MAAnalyticsInfo,
  MAAnalyticsActionType,
  MAAnalyticsEventType,
  UniversalBridgeInfo,
  CookieInfo,
} from '../../js-miniapp-bridge/src';

import { MiniApp } from './miniapp';
import {
  MiniAppEvents,
  MiniAppKeyboardEvents,
  HostAppEvents,
} from './event-types';

/** @internal */
const miniAppInstance = new MiniApp();

export default miniAppInstance;
export {
  CustomPermission,
  CustomPermissionName,
  CustomPermissionStatus,
  CustomPermissionResult,
  Reward,
  ShareInfo,
  ScreenOrientation,
  AccessTokenData,
  Contact,
  Points,
  DownloadFileHeaders,
  HostEnvironmentInfo,
  Platform,
  MessageToContact,
  AuthorizationFailureError,
  AudienceNotSupportedError,
  DownloadFailedError,
  DownloadHttpError,
  InvalidUrlError,
  MiniAppError,
  SaveFailureError,
  ScopesNotSupportedError,
  MiniAppEvents,
  MiniAppKeyboardEvents,
  HostAppEvents,
  SecureStorageFullError,
  SecureStorageBusyError,
  SecureStorageUnavailableError,
  SecureStorageIOError,
  MiniAppSecureStorageEvents,
  CloseAlertInfo,
  HostThemeColor,
  ProductInfo,
  ProductPrice,
  PurchasedProductInfo,
  PurchaseFailedError,
  ConsumeFailedError,
  ProductNotFoundError,
  ProductPurchasedAlreadyError,
  UserCancelledPurchaseError,
  MAAnalyticsInfo,
  MAAnalyticsActionType,
  MAAnalyticsEventType,
  UniversalBridgeInfo,
  CookieInfo,
};
