version: 2
jobs: # a collection of steps
  build-sdk: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/mini-js-sdk # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies w/ Yarn
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: #run lint and check for formatting
          name: check
          command: yarn sdk lint
      - run: #compile the code
          name: compile
          command: yarn sdk compile
      - run: # run tests
          name: test
          command: yarn sdk test
      - run: # run coverage report
          name: code coverage
          command: yarn sdk coverage
      - run: # upload coverage report
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts
          path: test-results
          prefix: tests
      - store_artifacts: # for display in Artifacts
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary
          path: test-results
      - persist_to_workspace:
          root: ~/mini-js-sdk
          paths:
            - js-miniapp-sdk/build/

  publish-sdk:
    working_directory: ~/mini-js-sdk
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: publish to NPM
          command: | 
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            yarn sdk publish 
      - run:
          name: Publish Documentation
          command: |
            set -e
            yarn sdk docs
            if [[ ! $CIRCLE_TAG == *"-"* ]]; then
              git checkout gh-pages
              cp -R publishableDocs/docs/. ./docs
              cp -R publishableDocs/_versions. ./_versions
              git add docs _versions
              git config user.name "CI Publisher"
              git config user.email "dev-opensource@mail.rakuten.com"
              git commit -m "Publish documentation for $CIRCLE_TAG"
              git push origin gh-pages
            else
              echo "Documentation not published for snapshot version"
            fi

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-sdk:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - sdk-release-verification:
          type: approval
          requires:
            - build-sdk
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-sdk:
          requires:
            - sdk-release-verification
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/