const SET_UNIQUE_ID = 'SET_UNIQUE_ID';
const SET_CONTACT_ID = 'SET_CONTACT_ID';
const SET_MAUID = 'SET_MAUID';
const UNIQUE_ID_FETCH_ERROR = 'UNIQUE_ID_FETCH_ERROR';
const CONTACT_ID_FETCH_ERROR = 'CONTACT_ID_FETCH_ERROR';
const MAUID_FETCH_ERROR = 'MAUID_FETCH_ERROR';
export { SET_UNIQUE_ID, SET_CONTACT_ID, SET_MAUID, UNIQUE_ID_FETCH_ERROR, CONTACT_ID_FETCH_ERROR, MAUID_FETCH_ERROR };
