const SET_MESSAGE_UNIQUE_ID = 'SET_MESSAGE_UNIQUE_ID';
const MESSAGE_UNIQUE_ID_FETCH_ERROR = 'MESSAGE_UNIQUE_ID_FETCH_ERROR';
const SET_MAUID = 'SET_MAUID';
const MAUID_FETCH_ERROR = 'MAUID_FETCH_ERROR';
export { SET_MESSAGE_UNIQUE_ID, SET_MAUID, MESSAGE_UNIQUE_ID_FETCH_ERROR, MAUID_FETCH_ERROR };
