// flow-typed signature: 81f3b6b0e236d69f2b1f7d5dfa9c1f9b
// flow-typed version: <<STUB>>/@brightcove/react-player-loader_v^1.4.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brightcove/react-player-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brightcove/react-player-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader.cjs' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader.es' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader.min' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/docs/api/scripts/linenumber' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/docs/api/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/docs/api/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/scripts/karma.conf' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/scripts/rollup.config' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/src' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/test/dist/bundle' {
  declare module.exports: any;
}

declare module '@brightcove/react-player-loader/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader.cjs.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/dist/brightcove-react-player-loader.cjs'>;
}
declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader.es.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/dist/brightcove-react-player-loader.es'>;
}
declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/dist/brightcove-react-player-loader'>;
}
declare module '@brightcove/react-player-loader/dist/brightcove-react-player-loader.min.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/dist/brightcove-react-player-loader.min'>;
}
declare module '@brightcove/react-player-loader/docs/api/scripts/linenumber.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/docs/api/scripts/linenumber'>;
}
declare module '@brightcove/react-player-loader/docs/api/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/docs/api/scripts/prettify/lang-css'>;
}
declare module '@brightcove/react-player-loader/docs/api/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/docs/api/scripts/prettify/prettify'>;
}
declare module '@brightcove/react-player-loader/scripts/karma.conf.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/scripts/karma.conf'>;
}
declare module '@brightcove/react-player-loader/scripts/rollup.config.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/scripts/rollup.config'>;
}
declare module '@brightcove/react-player-loader/src/index' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/src'>;
}
declare module '@brightcove/react-player-loader/src/index.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/src'>;
}
declare module '@brightcove/react-player-loader/test/dist/bundle.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/test/dist/bundle'>;
}
declare module '@brightcove/react-player-loader/test/index.test.js' {
  declare module.exports: $Exports<'@brightcove/react-player-loader/test/index.test'>;
}
