const SET_HOST_ENVIRONMENT_INFO = 'SET_HOST_ENVIRONMENT_INFO';
const HOST_ENVIRONMENT_INFO_FETCH_ERROR = 'HOST_ENVIRONMENT_INFO_FETCH_ERROR';

export { SET_HOST_ENVIRONMENT_INFO, HOST_ENVIRONMENT_INFO_FETCH_ERROR };