const REQUEST_PRODUCT_PURCHASE_SUCCESS = 'REQUEST_PRODUCT_PURCHASE_SUCCESS';
const REQUEST_PRODUCT_PURCHASE_FAILURE = 'REQUEST_PRODUCT_PURCHASE_FAILURE';

export { REQUEST_PRODUCT_PURCHASE_SUCCESS, REQUEST_PRODUCT_PURCHASE_FAILURE };