// flow-typed signature: 18cd1a5ac112bbe620a747b792fb029c
// flow-typed version: <<STUB>>/js-miniapp-sdk_v^1.1.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-miniapp-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-miniapp-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/common-bridge' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/common-log' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/ad-types' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/contact' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/custom-permissions' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/device-permission' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/download-file-headers' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/auth-errors' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/download-file-errors' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/mini-app-error' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/secure-storage-errors' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/host-environment-info' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/message-to-contact' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/platform' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/points' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types/rewarded' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/screen' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/secure-storage' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/share-info' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/token-data' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/event-types' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/miniapp' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/chat-service' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/secure-storage' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/user-info' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/utils' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/js-miniapp-sdk/test/miniapp.spec' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/build/miniapp.bundle' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/prettier.config' {
  declare module.exports: any;
}

declare module 'js-miniapp-sdk/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/common-bridge.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/common-bridge'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/common-log.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/common-log'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/ad-types/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/ad-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/ad-types/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/ad-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/contact.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/contact'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/custom-permissions.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/custom-permissions'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/device-permission.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/device-permission'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/download-file-headers.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/download-file-headers'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/auth-errors.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/auth-errors'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/download-file-errors.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/download-file-errors'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/mini-app-error.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/mini-app-error'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/secure-storage-errors.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/error-types/secure-storage-errors'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/host-environment-info.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/host-environment-info'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/message-to-contact.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/message-to-contact'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/platform.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/platform'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/points.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/points'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types/rewarded/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types/rewarded'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types/rewarded/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/response-types/rewarded'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/screen.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/screen'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/secure-storage.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/secure-storage'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/share-info.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/share-info'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-bridge/src/types/token-data.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-bridge/src/types/token-data'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/event-types/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src/event-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/event-types/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src/event-types'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/index' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/index.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/miniapp.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src/miniapp'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/chat-service.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/chat-service'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/secure-storage.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/secure-storage'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/user-info.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src/modules/user-info'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/src/utils.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/src/utils'>;
}
declare module 'js-miniapp-sdk/build/js-miniapp-sdk/test/miniapp.spec.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/js-miniapp-sdk/test/miniapp.spec'>;
}
declare module 'js-miniapp-sdk/build/miniapp.bundle.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/build/miniapp.bundle'>;
}
declare module 'js-miniapp-sdk/prettier.config.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/prettier.config'>;
}
declare module 'js-miniapp-sdk/test/setup.js' {
  declare module.exports: $Exports<'js-miniapp-sdk/test/setup'>;
}
